Traceback (most recent call last):
  File "C:\Users\WAI\Documents\surdarla.github.io\.venv\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\WAI\Documents\surdarla.github.io\.venv\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WAI\Documents\surdarla.github.io\.venv\Lib\site-packages\jupyter_core\utils\__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WAI\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\WAI\Documents\surdarla.github.io\.venv\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\WAI\Documents\surdarla.github.io\.venv\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\WAI\Documents\surdarla.github.io\.venv\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# sol
cal = [0] * 365
for _ in range(n):
    s, e = map(int, input().split())
    for i in range(s - 1, e):
        cal[i] += 1

result = 0
i = 0
while i < 365:
    if cal[i] > 0:
        width = 0
        height = 0
        while i < 365 and cal[i] > 0:
            width += 1
            height = max(height, cal[i])
            i += 1
        result += width * height
    else:
        i += 1
        
print(result)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mValueError[0m                                Traceback (most recent call last)
Cell [1;32mIn[4], line 4[0m
[0;32m      2[0m cal [38;5;241m=[39m [[38;5;241m0[39m] [38;5;241m*[39m [38;5;241m365[39m
[0;32m      3[0m [38;5;28;01mfor[39;00m _ [38;5;129;01min[39;00m [38;5;28mrange[39m(n):
[1;32m----> 4[0m     s, e [38;5;241m=[39m [38;5;28mmap[39m([38;5;28mint[39m, [38;5;28minput[39m()[38;5;241m.[39msplit())
[0;32m      5[0m     [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m [38;5;28mrange[39m(s [38;5;241m-[39m [38;5;241m1[39m, e):
[0;32m      6[0m         cal[i] [38;5;241m+[39m[38;5;241m=[39m [38;5;241m1[39m

[1;31mValueError[0m: not enough values to unpack (expected 2, got 0)

