Traceback (most recent call last):
  File "c:\users\wai\appdata\local\programs\python\python37\lib\site-packages\jupyter_cache\executors\utils.py", line 64, in single_nb_execution
    **kwargs,
  File "c:\users\wai\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\wai\appdata\local\programs\python\python37\lib\site-packages\jupyter_core\utils\__init__.py", line 98, in wrapped
    return loop.run_until_complete(inner)
  File "c:\users\wai\appdata\local\programs\python\python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\wai\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 706, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\wai\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\users\wai\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from manim import *
from manim import config; config.media_embed=True
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_3940\2253577653.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [1;32mfrom[0m [0mmanim[0m [1;32mimport[0m [1;33m*[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [1;32mfrom[0m [0mmanim[0m [1;32mimport[0m [0mconfig[0m[1;33m;[0m [0mconfig[0m[1;33m.[0m[0mmedia_embed[0m[1;33m=[0m[1;32mTrue[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'manim'

